"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const enderecoClienteController_1 = require("../controllers/enderecoClienteController");
const router = (0, express_1.Router)();
router.get('/clientes/:id/enderecos', enderecoClienteController_1.getEnderecosPorCliente);
router.post('/enderecos', enderecoClienteController_1.createEndereco);
router.put('/enderecos/:id', enderecoClienteController_1.updateEndereco);
router.delete('/enderecos/:id', enderecoClienteController_1.deleteEndereco);
exports.default = router;
