"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const itemPedidoController_1 = require("../controllers/itemPedidoController");
const router = (0, express_1.Router)();
router.get('/itens-pedido', itemPedidoController_1.getItensPedido);
router.get('/pedidos/:id/itens', itemPedidoController_1.getItensPorPedido);
router.post('/itens-pedido', itemPedidoController_1.createItemPedido);
router.put('/itens-pedido/:id', itemPedidoController_1.updateItemPedido);
router.delete('/itens-pedido/:id', itemPedidoController_1.deleteItemPedido);
exports.default = router;
